CREATE INDEX ASYNC IF NOT EXISTS idx_accounts_user ON accounts(user_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_messages_account ON messages(account_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_messages_account_summary_seen ON messages(account_id, summary_seen_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_messages_account_forward_seen ON messages(account_id, forward_seen_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_user_identities_user ON user_identities(user_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_user_identities_email ON user_identities(email_at_link);
CREATE INDEX ASYNC IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_category_definitions_user ON category_definitions(user_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_category_definitions_user_sort ON category_definitions(user_id, sort_order, slug);
CREATE INDEX ASYNC IF NOT EXISTS idx_message_categories_account ON message_categories(account_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_message_categories_message ON message_categories(message_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_message_categories_category ON message_categories(category_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_summary_snapshots_user_account ON summary_snapshots(user_id, account_id, created_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_summary_snapshots_run ON summary_snapshots(run_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_summary_job_chunks_run ON summary_job_chunks(run_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_action_items_user_status ON action_items(user_id, status, created_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_action_items_run ON action_items(run_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_fyi_items_run ON fyi_items(run_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_fyi_items_user_created ON fyi_items(user_id, created_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_draft_suggestions_user_created ON draft_suggestions(user_id, created_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_draft_suggestions_action_item ON draft_suggestions(action_item_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_send_attempts_user_created ON send_attempts(user_id, created_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_forward_rules_user_account ON forward_rules(user_id, account_id, enabled);
CREATE INDEX ASYNC IF NOT EXISTS idx_forward_audit_user_created ON forward_audit(user_id, created_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_forward_audit_run ON forward_audit(run_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_manual_forward_audit_user_created ON manual_forward_audit(user_id, created_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_schedule_chains_user ON schedule_chains(user_id, updated_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_schedule_chains_due ON schedule_chains(enabled, next_run_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_organisation_members_user ON organisation_members(user_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_contacts_org ON contacts(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_contacts_org_name ON contacts(organisation_id, display_name);
CREATE INDEX ASYNC IF NOT EXISTS idx_contact_identities_contact ON contact_identities(contact_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_corr_part_message ON correspondence_participants(message_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_corr_part_contact ON correspondence_participants(contact_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_corr_part_manual_item ON correspondence_participants(manual_item_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_projects_org ON projects(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_project_members_user ON project_members(user_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_thread_assignments_org ON thread_assignments(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_msg_overrides_org ON message_assignment_overrides(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_manual_items_org ON manual_items(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_manual_items_project ON manual_items(project_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_manual_items_occurred ON manual_items(occurred_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_issues_project ON issues(project_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_issues_org ON issues(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_issue_items_issue ON issue_items(issue_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_facts_project ON facts(project_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_facts_org ON facts(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_fact_versions_fact ON fact_versions(fact_id, status);
CREATE INDEX ASYNC IF NOT EXISTS idx_fact_evidence_version ON fact_evidence(fact_version_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_fact_evidence_message ON fact_evidence(message_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_fact_evidence_manual ON fact_evidence(manual_item_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_interpretations_project_status ON interpretations(project_id, status);
CREATE INDEX ASYNC IF NOT EXISTS idx_interpretations_org ON interpretations(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_interpretation_sources_interp ON interpretation_sources(interpretation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_interpretation_sources_message ON interpretation_sources(message_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_interpretation_sources_manual ON interpretation_sources(manual_item_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_interpretation_sources_connector ON interpretation_sources(connector_message_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_contradictions_project_status ON contradictions(project_id, status);
CREATE INDEX ASYNC IF NOT EXISTS idx_contradictions_org ON contradictions(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_contradiction_sides_contradiction ON contradiction_sides(contradiction_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_decisions_project_status ON decisions(project_id, status);
CREATE INDEX ASYNC IF NOT EXISTS idx_decisions_org ON decisions(organisation_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_decision_evidence_decision ON decision_evidence(decision_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_connector_accounts_user ON connector_accounts(user_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_connector_bindings_account ON connector_bindings(connector_account_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_connector_bindings_project ON connector_bindings(project_id);
CREATE INDEX ASYNC IF NOT EXISTS idx_connector_messages_project_occurred ON connector_messages(project_id, occurred_at);
CREATE INDEX ASYNC IF NOT EXISTS idx_connector_messages_account ON connector_messages(connector_account_id);
